name: Hugo Auto Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.7'  # 固定稳定版本
          extended: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/hugo
            resources/_gen
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/go.mod') }}

      - name: Build site
        run: |
          hugo --minify \
               --cleanDestinationDir \
               --baseURL "https://loopsteam.github.io/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: loopsteam/loopsteam.github.io
          publish_branch: main
          publish_dir: ./public
          commit_message: "🚀 Deploy: ${{ github.sha }}"
          full_commit_message: |
            ${{ github.event.head_commit.message }}
            [ci skip] Auto deploy via GitHub Actions 